const types = {

    GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
    GET_COUNTRY_SUCCESS: 'GET_COUNTRY_SUCCESS',
    GET_COUNTRY_FAILURE: 'GET_COUNTRY_FAILURE',

    GET_LATEST_RATES_REQUEST: 'GET_LATEST_RATES_REQUEST',
    GET_LATEST_RATES_SUCCESS: 'GET_LATEST_RATES_SUCCESS',
    GET_LATEST_RATES_FAILURE: 'GET_LATEST_RATES_FAILURE',

}


export default types