const types = {

    GET_COUNTRY_REQUEST: 'GET_COUNTRY_REQUEST',
    GET_COUNTRY_SUCCESS: 'GET_COUNTRY_SUCCESS',
    GET_COUNTRY_FAILURE: 'GET_COUNTRY_FAILURE',

    GET_LATEST_RATES_REQUEST: 'GET_LATEST_RATES_REQUEST',
    GET_LATEST_RATES_SUCCESS: 'GET_LATEST_RATES_SUCCESS',
    GET_LATEST_RATES_FAILURE: 'GET_LATEST_RATES_FAILURE',

    GET_SYMBOLS_REQUEST: "GET_SYMBOLS_REQUEST",
    GET_SYMBOLS_SUCCESS: "GET_SYMBOLS_SUCCESS",
    GET_SYMBOLS_FAILURE: "GET_SYMBOLS_FAILURE",

    HANDLE_SEND_DATA_TO_TABLE: "HANDLE_SEND_DATA_TO_TABLE"
}


export default types